### ISSUE TITLE
Guard Canonicalization is invalid

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/calyx#1010]
Consider the following two sets of assignments:
```
w.in = a.out ? 1'd1;
w.in = b.out ? 1'd1;
```
and
```
w.in = a.out;
w.in = b.out;
```

In the first program, we're saying something like: if `a.out` or `b.out` is active, forward `1'd1` to `w.in`, otherwise forward nothing. In the second program, we're saying unconditionally forward both `a.out` and `b.out` to `w.in` which is an obvious runtime conflict.

The first program can be optimized into:
```
w.in = a.out | b.out ? 1'd1;
```

However, the canonicalization pass currently transforms program (1) to (2), altering the semantics. We should disable rewrites of the form `a = g ? 1'd1 -> a = g` and instead only allow the canonicalizer to perform `a = 1'd1 ? b` to `a = b`.

**Comment by sampsyo** [comment]
It's a good example, and I think it clearly depends on nailing down semantics for undefinedness as suggested in #922… namely, I don't think it's a foregone conclusion that this is always a conflict:

```
w.in = a.out;
w.in = b.out;
```

We don't right now, but we could decide that this is perfectly safe _if_ `a.out` and `b.out` are never defined simultaneously.
