### ISSUE TITLE
Error when trying to use `--to resource-estimate`

### ISSUE THREAD

**Issue by gussmith23** [cucapra/calyx#1059]
When I run:

```sh
RUST_BACKTRACE=full fud e --to resource-estimate examples/futil/dot-product.futil >calyx-error.log 2>&1
```

I get the output shown in the logfile attached!

[calyx-error.log](https://github.com/cucapra/calyx/files/9006493/calyx-error.log)

Thanks for the awesome tool!!!

**Comment by rachitnigam** [comment]
https://github.com/cucapra/calyx/pull/1056 fixes this!

**Comment by gussmith23** [comment]
you guys rock!!!
