### ISSUE TITLE
Correct width mismatches between memory controller and `x_addr0`

### ISSUE THREAD

**Issue by nathanielnrn** [cucapra/calyx#1081]

**Comment by nathanielnrn** [comment]
I've made some progress on this and _seem_ to be able to generate parametrically sized brams in a given axi-memory-controller. I still have to correctly wire up the memory controllers to the correct brams but it should be doable.

The thing is, I'm not really happy with my implementation. There is quite a lot of code duplication and it's a pretty hacky way of making things wortk. I was wondering if I should open a draft PR to get some notes from @rachitnigam or @sampsyo (or anyone else) on things before I go any further?

**Comment by rachitnigam** [comment]
Yeah, draft PR would be a good idea
