### ISSUE TITLE
Consider changing `seq_mem` port names

### ISSUE THREAD

**Issue by andrewb1999** [cucapra/calyx#1286]
Currently `std_mem` has port names `read_data` and `write_data`. `seq_mem` uses the names `in` and `out` instead. Is there a good reason for this change? It seems to me that `read_data` and `write_data` are clearer and more inline with what RTL users would expect.

This is relevant when adding `seq_mem` to CIRCT.

**Comment by rachitnigam** [comment]
Seems reasonable! The only annoying thing would be coordinating the change between Dahlia and this repo

**Comment by rachitnigam** [comment]
Hey @calebmkim, this might be a good issue to work on next. We'll need to change the names of the ports and update the Dahlia backend to use the new names
