### ISSUE TITLE
[CIRCT] Add Godbolt example to Calyx IR website.

### ISSUE THREAD

**Issue by cgyurgyik** [cucapra/calyx#1379]
@mikeurbach added Godbolt support for CIRCT. I think it is a great way to demonstrate Calyx, and reproduce bugs. I've constructed a small example of an optimization available in the CIRCT dialect: 

https://godbolt.org/z/c6YW6MT97

It seems that emit-calyx isn't available yet as a command line argument. Perhaps one day we can add support for that as well (unsure what exactly this entails). In any case, thanks Mike! This is super cool work.

**Comment by mikeurbach** [comment]
I believe the version of CIRCT used in Compiler Explorer was built once from CIRCT main and hasn't been updated. I'm not sure how the Compiler Explorer folks support trunk based development like CIRCT and LLVM use, but perhaps we can trigger another build so a more recent CIRCT is available. I'm not sure what MLIR does in Compiler Explorer, but it must be the same story.
