### ISSUE TITLE
[Compiler / IL] Current string interner is thread-unsafe

### ISSUE THREAD

**Issue by EclecticGriffin** [cucapra/calyx#1401]
Just documenting an issue we discussed in person earlier.

Introduced in #1310, the IDs currently used by Calyx are very thread unsafe, which means the Calyx IL cannot currently be used in any threaded contexts, though it does not indicate this.

The root issue is that the singleton method allows multiple mutable accesses to the string interner which can result in erratic behavior and wild memory corruption. I.e., does not enforce the exclusivity of the mutable reference.

The solution requires some form of synchronization.

**Comment by sampsyo** [comment]
Thank you! I believe the low-hanging approach here is to replace our use of `string-interner` with [the larger `symbol_table` crate](https://crates.io/crates/symbol_table) that uses it but is thread safe. Quoting @rachitnigam from https://github.com/cucapra/calyx/pull/1310#issuecomment-1356147222:

> This is because symbol_table is written with multi-threaded use in mind and adds overhead for locking and sharding because of that.

"Multi-threaded use in mind" is exactly what we want.
