### ISSUE TITLE
Broken link in top-level README

### ISSUE THREAD

**Issue by anshumanmohan** [cucapra/calyx#1478]
In two places in the top-level README, we point to https://docs.calyxir.org/source/calyx. This is a broken link. Not sure where you wanted it to point, so I'm making a quick issue for you to knock out!

The reference to fix is:
```
[source-docs]: https://docs.calyxir.org/source/calyx
```

**Comment by rachitnigam** [comment]
It refers to a locally hosted version of [source code documentation](https://docs.rs/calyx-ir/0.2.0/calyx_ir/) which documents the internal Rust IR structures.
