### ISSUE TITLE
Tutorial: assets needed

### ISSUE THREAD

**Issue by anshumanmohan** [cucapra/calyx#1479]
This is a tracking issue for all the non-core assets we need at hand for the tutorial. I've added some provisional assignments, but let's discuss!

- Intro, setup, first Calyx program @rachitnigam
    - [x] Probably don't need any slides
    - [x] #1194 
- Pollen @susan-garry
    - [ ] 5 min talk
- Cider @EclecticGriffin 
    - [ ] 5 min talk
- `fud` // many folks are able to give a talk about this
    - [ ] 5 min talk
- Competition: educational materials @anshumanmohan 
    - Memory banking
        - [x] Slides explaining what MrXL is already doing (and why)
        - [x] Simple one-page handout
    - Reduction trees
        - [x] #1414 
        - [x] Slides explaining what’s going on, plus extensions (pipelining, generalizing for any parallelization factor)
        - [x] Simple one-page handout
    - Arbitration logic
        - [x] #1474 
        - [x] Slides explaining what’s going on, and how this stuff, if generalized, aids #1472 
        - [x] Simple one-page handout

**Comment by anshumanmohan** [comment]
[Here](https://www.icloud.com/keynote/074tC5fuawyy4GQLUdCOV6IdA#red%5Ftrees) are some slides as a primer for reduction trees. Seeking feedback at any level! One flaw is that folks _need_ the animation right now; the slides viewed statically all look the same. I'll add "Day {i}" annotations to the matches. I just wanted your thoughts before getting too deep into it.

**Comment by anshumanmohan** [comment]
And [here](https://www.icloud.com/keynote/093n5xPkBNJoS26zentQwE-_w#banking%5Fand%5Farbitrage) are further slides, this time explaining memory banking and arbitrage. Same deal: I have ideas about how to make these less reliant on animation, but I'm looking for general commentary before going too deep.

**Comment by rachitnigam** [comment]
Thanks for getting us started @anshumanmohan! Just as a suggestion for the rest of us, maybe we should just have one slide deck and create "sections" in it for our various talks? It would centralize our efforts and simplify things!

**Comment by sampsyo** [comment]
It seems 100% fine to rely on animation for the slides, FWIW! If people want to view them "statically" for reference, you can export to PDF from Keynote with the "print every stage of builds" option enabled.

**Comment by anshumanmohan** [comment]
Update, I've mashed my slides into one .key. I've changed the link and the text above

**Comment by anshumanmohan** [comment]
@rachitnigam, reminder to change the [schedule](https://calyxir.org/tutorial/) to give Cider 5 mins

**Comment by anshumanmohan** [comment]
In view of the changes I've made to the frontend tutorial, I propose a change to the schedule.

Right now we have
10am-10.05am | MrXL: A map-reduce frontend
10.05am-11am | Compiling MrXL to Calyx

And I think we could instead have
10am-10.15am | MrXL: A map-reduce frontend
10.15am-11am | Add your own extensions to MrXL

That is, in the first 15 mins, we'll walk them through the tutorial as written. We will gloss over the parts where the tutorial shows how to compile MrXL using the eDSL, since that's really best for working through yourself. Someone lecturing that same stuff at you won't help.

Then we'll leave 45 mins for them to add one of the "warmup" extensions to MrXL. This will put them in a good place to add a real extension later on.

**Comment by anshumanmohan** [comment]
Speaking of later on, I propose that we change

> 11.25am-12.25pm | Hardware Performance 101 / MrXL competition

into three tracks.

1. Reduction trees, for those interested in speedup. 
2. Arbitration and multi-banking, for those interested in that.
3. Office hours, for those just wanting to backfill about what the heck is going on.

**Comment by anshumanmohan** [comment]
I dry-ran the tutorial exactly as written, with the exception that I skipped to the not-yet-merged branch [mrxl-input-dynamic](https://github.com/cucapra/calyx/tree/mrxl-input-dynamic) when it came time to do MrXL stuff.

I have flagged my issues here: https://github.com/cucapra/calyx/issues/1508. After those issues are fixed, someone else should do a dry run.

**Comment by priyasrikumar** [comment]
I can own fixing those issues! Most of them seem doable but will ping others if there are any issues with resolving those. I will also do the tutorial dry run after that and see if there are any other hiccups!!

**Comment by rachitnigam** [comment]
Should we consider this completed?

**Comment by anshumanmohan** [comment]
Yup!
