### ISSUE TITLE
`futil` deprecation: rename `fud` flag

### ISSUE THREAD

**Issue by anshumanmohan** [cucapra/calyx#1484]
In the vein of #1454, we could deprecate `fud`'s `--to futil` in favor of `--to calyx`. This is a very minor low-priority thing that will probably break things everywhere, so feel free to punt on it!

**Comment by rachitnigam** [comment]
Yeah, seems reasonable! In addition to this, we should rename the `FutilStage` class to `CalyxStage`. @anshumanmohan you are right: it will probably break a bunch of things but it's also not too hard to fix them.
