### ISSUE TITLE
MrXL Tutorial Extensions

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/calyx#1516]
We should provide more specific information for each bullet point mentioned in ["Further Steps"](https://docs.calyxir.org/tutorial/frontend-tut.html#further-steps). For each bullet point, we should have a short paragraph explaining *why* there is a restriction, *how* to remove it, and *what* tools users have at hand to attempt the extension (primitives, examples, etc.)

**Comment by anshumanmohan** [comment]
On realizing that a relatively deeper dive is needed, I am un-assigning myself 😅
