### ISSUE TITLE
Builder: `par` generation is non-deterministic

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/calyx#1517]
@EclecticGriffin we talked about this but not sure if this was already addressed since #1503 seems to run into this.

**Comment by EclecticGriffin** [comment]
This is fixed if you use the `par(...)` constructor over the set literal. We may want to deprecate/remove the set literal construction

**Comment by rachitnigam** [comment]
Let's remove it. The current docs use it and it's not correct: https://docs.calyxir.org/calyx-py.html

Also, CC @priyasrikumar to change this

**Comment by EclecticGriffin** [comment]
see: https://github.com/cucapra/calyx/pull/1503/files#r1204378462

**Comment by sampsyo** [comment]
It's probably a good idea to remove the set trick! It was too cute to live. Especially since @EclecticGriffin wisely added an explicit `par`, as referenced above.
