### ISSUE TITLE
Tutorial: Specific Docker tag

### ISSUE THREAD

**Issue by anshumanmohan** [cucapra/calyx#1558]
We want to give the users a specific Docker tag to pull, not just `latest`, but we don't yet know which Docker tag that should be. Making an issue so we don't forget.

_Originally posted by @anshumanmohan in https://github.com/cucapra/calyx/issues/1556#issuecomment-1581608273_

**Comment by rachitnigam** [comment]
We've released a new image [`0.3.0-FCRC`](https://github.com/cucapra/calyx/pkgs/container/calyx/101183940?tag=0.3.0-FCRC)

**Comment by anshumanmohan** [comment]
Reopening: gotta update docs to reflect this.
