### ISSUE TITLE
Support creating a workspace from multiple top-level files

### ISSUE THREAD

**Issue by bcarlet** [cucapra/calyx#1599]
The existing constructor for `frontend::Workspace` only accepts a single file path. That makes it awkward to construct a workspace from multiple top-level files, e.g., when importing multiple standard library files. One has to parse each of them individually and then merge the workspaces, which also results in a lot of duplicated parsing when the files have common dependencies.

The code to do this efficiently is already embedded in the implementation of `Workspace::construct_with_all_deps()`, it just needs to be exposed as part of the public interface.

**Comment by rachitnigam** [comment]
This should be super straightforward! We can just make the method `pub` and create a new minor release. @bcarlet want to take a shot?
