### ISSUE TITLE
Registers passed as `ref` cells: update docs, eDSL

### ISSUE THREAD

**Issue by anshumanmohan** [cucapra/calyx#1616]
Can registers be passed by reference? @sampsyo thinks yes. 

The [docs](https://docs.calyxir.org/lang/memories-by-reference.html) don't say anything to prevent it, but the worked example in the docs always uses memories. May be worth updating them to take a stand, even if Adrian is wrong.

The builder library currently prevents me from declaring a register with `is_ref=True`. If Adrian is right, let's fix it!

**Comment by rachitnigam** [comment]
Indeed! Any cell can be passed by reference
