### ISSUE TITLE
Width does not implement PartialEq

### ISSUE THREAD

**Issue by UnsignedByte** [cucapra/calyx#1620]
As described in the title, the Width enum (used in PortDef) does not implement the PartialEq trait. This would be helpful for filament which happens to need it when compiling to calyx (referenced in https://github.com/cucapra/filament/pull/186#discussion_r1269804184).

This might need some discussion as constant widths and param widths can't really be compared but it would be useful to be able to determine if two constant widths or parameter widths are equal.

**Comment by rachitnigam** [comment]
Thanks for opening the issue @UnsignedByte! This should be pretty easy to change; do you want to open a PR fixing this?
