### ISSUE TITLE
Builder: generate names

### ISSUE THREAD

**Issue by anshumanmohan** [cucapra/calyx#1635]
It would be cool if the builder had a central "gensym" utility for generating fresh names. Then these utilities wouldn't need to take in a group and cell name (or at least they could be optional); the builder would just call them `lt1234` or whatever automatically.

_Originally posted by @sampsyo in https://github.com/cucapra/calyx/pull/1630#discussion_r1272919454_

**Comment by rachitnigam** [comment]
Great Idea! The `ir::Namegenerator` struct does this for the Rust-based builder/
