### ISSUE TITLE
Builder: further steps

### ISSUE THREAD

**Issue by anshumanmohan** [cucapra/calyx#1636]
The Builder library has gotten a little more attention of late, and we've spawned a few little tasks that I'm afraid will get lost. This is the tracker issue I think we need.

- [x] #1638
- [x] #1637
- [x] #1635 

_Originally posted by @anshumanmohan in https://github.com/cucapra/calyx/issues/1630#issuecomment-1648335727_

**Comment by rachitnigam** [comment]
Thanks @anshumanmohan! Can you create a "Comp: calyx-py" label and tag the relevant issues with it so that we have an easy way of filtering things?
