### ISSUE TITLE
Stability requirement for condition ports

### ISSUE THREAD

**Issue by bcarlet** [cucapra/calyx#1700]
I recently encountered the somewhat strange stability requirement that is currently present for condition ports, namely, that the port must be stable only if the `if`/`while` statement lacks a combinational group. That leads to some odd behavior, for instance, a program that is rejected under these rules can be made legal simply by adding an empty combinational group (in particular, one that does not write to the condition port).

The implications/oddities arising from this have already been discussed in #1438 and #1467, but I couldn't find an issue about it so I've created this one.

From a user's perspective, it would be nice to allow conditions that are not stable themselves, nor necessarily calculated in a combinational group, but are nonetheless combinational functions of stable ports. That would basically amount to the stability propagation @sampsyo proposed [here](https://github.com/cucapra/calyx/pull/1467#issuecomment-1546940146).

**Comment by sampsyo** [comment]
Closing this in favor of #1699, where things are starting to converge but still somewhat unresolved.
