### ISSUE TITLE
Merge std_div_pipe and std_mod_pipe

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/calyx#330]
Both run the same algorithms but place different things on the output ports. Just merge them and expose two output ports. Once we add the `share` attribute on them, instances of `div` and `mod` would become shareable. 

- [ ] Merge definitions of primitives in library
- [ ] Update the Dahlia compiler to use the newly added ports

**Comment by sampsyo** [comment]
Good idea. Just for fun, reminds me of `div` and `div_t` in C. https://en.cppreference.com/w/cpp/numeric/math/div
