### ISSUE TITLE
Make primitives use invokable go-done interface

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/calyx#331]
The invokable go-done interface states that the outputs from an invoked component stay available till the next invocation. Currently, out primitive library modules don't follow this convention. Instead, they usually reset their output after `done == 0`. 
Change this and make them invokable.

Once primitives are invokable, they also become `share`able.

- [x] `std_mult_pipe`
- [ ] `std_mod_pipe` and `std_div_pipe` (after #330)
- [x] `std_sqrt`

**Comment by cgyurgyik** [comment]
For my understanding, how exactly is the `mult_pipe` made invokable without creating a latch? I was thinking an extra boolean value in the if statement that checks to see the operation has been run once, but I'm not entirely convinced that's correct.

**Comment by rachitnigam** [comment]
As far as I know, there isn't a way to do this without adding a latch.
