### ISSUE TITLE
Represent bounded loops in Calyx

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/calyx#338]
During `static-timing` compilation, all loops are assumed to be unbounded and given no `"static"` attribute. This means that control sub-programs with `while` and components with `while` cannot be statically compiled since the requirement of static compilation is all children be statically compilable.

However, Dahlia has `for` loops which are always bounded. Similarly, there might be other backends that want to represent bounded loops and take advantage of static compilation. We have two options:

1. Introduce a new `repeat` control operator that desugars to plain `while` loops (making it a so-called "level-2" operator). The repeat operator would run the control sub-program a finite number of times and can be statically compiled.
2. Add attributes to the control language (extension of #311) and give `while` loops an attribute (`"repeats"`) which specifies the number of iterations the loop is expected to take.

**Comment by rachitnigam** [comment]
How about:
```
@bound(12) while le.out with cond0 { ... }
```

Where the `@bound(12)` says that the loop runs 12 times.

**Comment by sampsyo** [comment]
Sounds excellent to me! I like the attribute here a bit more than adding a whole new control construct because it keeps things a bit more orthogonal (bounded & unbounded can get compiled the same way). And a trip-count annotation does seem like the way to go, specifically.

**Comment by rachitnigam** [comment]
@ai-cu are you working on this? If so, please assign yourself the issue and change the "status" label to "in-progress".
