### ISSUE TITLE
minimize-regs pass is probably broken for uses of registers in conditions of `if` and `while`

### ISSUE THREAD

**Issue by sgpthomas** [cucapra/calyx#442]
The minimize regs pass doesn't rewrite the conditions of `if` and `while` loops. This means that if a register is used in the condition that was rewritten to something else, the program will no longer be correct because the register won't be updated in the way that is expected.

We should
 1) add a test case that checks for this (and verify that this is actually a problem)
 2) fix minimize regs to rewrite conds
 3) maybe implement a more general cell rewriting helper into the builder that does this automatically because this will be a problem for all passes that want to rewrite components

**Comment by sgpthomas** [comment]
verified the bug. here's a program that breaks (and causes the compiler to crash)
```
// -p minimize-regs -p dead-cell-removal
import "primitives/std.lib";
component main() -> () {
  cells {
    x = std_reg(1);
    y = std_reg(1);
  }

  wires {
    group wr_x {
      x.in = 1'd1;
      x.write_en = 1'd1;
      wr_x[done] = x.done;
    }

    group cond {
      y.in = 1'd1;
      y.write_en = 1'd1;
      cond[done] = y.done;
    }

    group some_math {
      y.in = 1'd0;
      y.write_en = 1'd1;
      some_math[done] = y.done;
    }
  }

  control {
    seq {
      wr_x;
      if y.out with cond {
        some_math;
      }
    }
  }
}
```

**Comment by sampsyo** [comment]
Good find! And nice work concocting a test case.
