### ISSUE TITLE
Dead cell removal removes cells that are used in invoke

### ISSUE THREAD

**Issue by sgpthomas** [cucapra/calyx#448]
This program:
```
import "primitives/std.lib";

component add(left: 32, right: 32) -> (out: 32) {
  cells {
    adder = std_add(32);
    outpt = std_reg(32);
  }
  wires {
    group do_add {
      adder.left = left;
      adder.right = right;
      outpt.in = adder.out;
      outpt.write_en = 1'd1;
      do_add[done] = outpt.done;
    }
  }
  control {
    seq {
      do_add;
    }
  }
}

component main() -> () {
  cells {
    my_add = add();
    y = std_reg(32);
  }
  wires {
    group wr_y {
      y.in = 32'd10;
      y.write_en = 1'd1;
      wr_y[done] = y.done;
    }
  }
  control {
    seq {
      wr_y;
      invoke my_add(left = y.out, right = y.out)();
    }
  }
}
```
removes `my_add` from the cells of main.

**Comment by rachitnigam** [comment]
`dead-cell-removal`, like every other optimization, assumes that `compile-invoke` has been run. Related to #355.

**Comment by sgpthomas** [comment]
does this remove the need for #355 then? if so we should close that issue and have the code fail instead of `unimplemented!()`

**Comment by sgpthomas** [comment]
if that's true, we should also have `dead-cell-removal` fail if there is an `invoke` in the control

**Comment by rachitnigam** [comment]
I don't think so. I think we should support `invoke` reasoning in all passes. I'm just saying that we should probably group this with #355.

**Comment by sgpthomas** [comment]
ah I see. discovered this while working on #355 so I agree
