### ISSUE TITLE
Should the [core] tests include the language tutorial?

### ISSUE THREAD

**Issue by cgyurgyik** [cucapra/calyx#500]
As noted by @sgpthomas, the language tutorial tests:

https://github.com/cucapra/calyx/blob/79825bb667496e9929933d74f9d50572913efb54/runt.toml#L185-L190

require `fud` to run. 

Potential options:
1. `fud` is considered a "core tool." 
2. The tests should be modified so that no core tests require `fud`.

**Comment by sgpthomas** [comment]
I think we should just make `fud` a core tool. It's nice to have the language tutorials be something that works with the `core` installation so that people can follow along.

**Comment by sampsyo** [comment]
TBH either direction seems equally cool to me!
