### ISSUE TITLE
First class reset signals

### ISSUE THREAD

**Issue by sgpthomas** [cucapra/calyx#501]
A first class notion of resetting components is important. Firstly, it's important for synthesizability. Cells need to be initialized to be a particular value. We can get initial values by resetting the component at the beginning of an execution. Secondly, resetting components can give the compiler more information about components. At the moment, it has to assume that any component can have arbitrary state and so the compiler can't prove it's save to share (maybe unshare too?) components. This is probably important for pipelining in some way too, but I haven't thought extensively about this.

Implementing this may remove the need for the fix for the zero-time reset bug we ran into with Verilator.

## Syntax
We should just use an annotation on a port in the signature. Something like `@reset(1)`. Does this signal
need to be explicitly passed to sub components? Or is it like `clk` which is magically threaded through. Do
components want to define custom reset behavior?

## Definition of Reset
The start of a definition. I don't know if this is complete:

if cells `A, B` are both reset instances of component `T`. Then, 
```
seq {
  invoke A(a_in)(a_out); 
  invoke B(b_in)(b_out);
}
```
is equivalent to
```
seq {
  invoke A(a_in)(a_out);
  reset_A;
  invoke A(b_in)(b_out);
}
```

**Comment by sampsyo** [comment]
This is a good point! It would be great to think carefully about the approach.

At a high level, my gut reaction is that it *should* need to be threaded through manually. The difference with the clock signal is that we have made a kind of implicit assumption that Calyx is all about *synchronous digital logic*, i.e., stuff like flip-flops are out of scope (below the Calyx level of abstraction). So unlike RTL, we can assume that everything is connected to one giant, global clock. But reset signals are semantically relevant to the core stuff that Calyx is supposed to address: values, state, and computation. So I think components should have the responsibility (and freedom!) to define for themselves what "resetting their state" means to them, semantically.

I can imagine two main ways to go about it:

- Adding an (optional?) reset signal that is analogous to the standard go and done signals. This would be the simpler way to go, but maybe it's limiting in some way? Can we think of situations where a simple, uniform 1-bit "calling convention" is too limiting? Maybe not, and this is just fine for a lot of possible components.
- Maybe we revisit the whole "methods" idea and consider supporting a reset "method call" on components. But of course that is a much bigger effort, so maybe we should leave this option for another time.
