### ISSUE TITLE
Replace `groups` and `cells` Vecs in Component with LinkedHashMaps

### ISSUE THREAD

**Issue by EclecticGriffin** [cucapra/calyx#514]
Replacing these will allow the `find_cell` and `find_group` methods to operate in constant time rather than linear time, but will preserve iteration order. The change is not likely to be complicated but will require a bunch of places to adjust to the new signature. It may be helpful to create a wrapper method on the component to allow mut/imut iteration over these fields, rather than exposing them directly, though if Ids are changed for some reason there is the danger that the key will become out of sync with the value. This perhaps deserves a little consideration, though it would be relatively straightforward, albeit in linear time, to update the keys to match the values. 

See following thread for initial info:

Can you talk a bit more about what this is amortizing exactly? Is it because the `find_cell` and `find_group` methods are linear? The right way to fix that is just to make them use a `LinearHashMap` and have constant access in those methods directly.

_Originally posted by @rachitnigam in https://github.com/cucapra/calyx/pull/511#discussion_r634451397_

**Comment by EclecticGriffin** [comment]
Upon consideration and discussion with Sam, it may make more sense to try to use a BTreeSet and define ordering & hashing over the RRCs based on their id. The main issue is that if we have the keys into a map be the ids of the corresponding group or cell then they could become out of sync with the value if someone changes the value's id.

**Comment by EclecticGriffin** [comment]
Should also wrap over this with an interface so that the particular implementation choices don't matter

**Comment by rachitnigam** [comment]
> The main issue is that if we have the keys into a map be the ids of the corresponding group or cell then they could become out of sync with the value if someone changes the value's id.

One way out of this is making the underlying `id` of groups and cells be a `pub(super)` to the `ir::` crate and expose a function called `id()` which only gives an immutable handle to the id, disallowing any changes to it.

> Should also wrap over this with an interface so that the particular implementation choices don't matter

Aren't `find_cell` and `find_group` that two interface methods that do this already?

**Comment by EclecticGriffin** [comment]
I think the `id()` idea would likely solve the main issue here. wrt to the second point, I meant iteration over the groups and cells through the component as well as replacing direct invocation of `push` on the underlying vector with some method on the component itself

**Comment by rachitnigam** [comment]
Got it. You're right—we should abstract those patterns.
