### ISSUE TITLE
Interpreter value types and primitives

### ISSUE THREAD

**Issue by ai-cu** [cucapra/calyx#523]
The issue concerning the development of the value types and primitives in the interpreter. TODOs:

__Primitives__
- [x] Struct definition for all the primitives
- [x] How to unify sequential and combinational primitives (builds on top of the above)

__Values__
- [x] Change from u64 to bit vectors so that we have more control over operations (everything bit-wise)

**Comment by EclecticGriffin** [comment]
Here's the crate I was talking about: https://docs.rs/bitvec/0.22.3/bitvec/vec/struct.BitVec.html
