### ISSUE TITLE
Multi-component simulation

### ISSUE THREAD

**Issue by sampsyo** [cucapra/calyx#538]
We should be able to simulate Calyx programs with more than one component! This issue is about the _structural_ version of multi-component programs (i.e., not using the `invoke` control operator). That is, you might have one component that "runs" a different component by explicitly assigning to its `go` port and then waiting for its `done` port to go from 0 to 1.

A challenge in this effort will be concurrency, i.e., running the "parent" component and the "child" component at the same time.

**Comment by rachitnigam** [comment]
It’s worth noting at this point that we need to decide if go/done signals for components are a part of the actual semantics or not. With the invoke operator, it is not actually necessary to have go/done signals in the semantics of non structural programs.

**Comment by sampsyo** [comment]
Indeed. I guess the default position is that they are required if you're running a component structurally but not for `invoke`. That's a little weird, TBH, but maybe a practical decision.
