### ISSUE TITLE
Represent undefined signals in the interpreter

### ISSUE THREAD

**Issue by sampsyo** [cucapra/calyx#542]
Currently, when a signal in a Calyx program doesn't have a meaningful value during interpretation, we currently just say that it has the value zero. For example, when a group is currently "disabled" (i.e., not running), all the stuff it assigns to gets a zero value.

But it actually seems a little odd to be using zero for all these port values—because it looks the same as if someone was explicitly/intentionally writing a zero to it! We should think carefully about how we want to represent "disabled" signals and probably change the interpreter environment to support "undefined" values for these cases. This will also involve figuring out how to represent undefinedness in the output serialization format from the interpreter.

**Comment by EclecticGriffin** [comment]
Closing this as stale for the moment, worth revisiting later on in the redesign efforts
