### ISSUE TITLE
Make intepreter tests that use more complex memories

### ISSUE THREAD

**Issue by EclecticGriffin** [cucapra/calyx#559]
We'll soon be able to print the full contents of the memory cells from the interpreter, so we should make sure that memories with more than one slot are behaving as expected.

**Comment by rachitnigam** [comment]
Since we can simulate all but 3 of the polybench benchmarks, should we consider this resolved @EclecticGriffin?

**Comment by EclecticGriffin** [comment]
That sounds good to me
