### ISSUE TITLE
Simplify the group interpreter

### ISSUE THREAD

**Issue by EclecticGriffin** [cucapra/calyx#561]
Splitting from #556. Currently the group interpreter is too clever for its own good (my fault) and approaches cells and assignments in a changed based way. Instead we should just run all assignments and execute all primitives during each loop of the simulation. This will likely be marginally more inefficient but less error prone and we can always re-optimize later.

**Comment by EclecticGriffin** [comment]
I have a sketch of this (and #556 as a necessary sub-step) visible in https://github.com/cucapra/calyx/tree/simplify_group_sim which matches the runt tests!

Still needs some cleanup and work, but may subsume some of the stuff @yn224 has been working on. I refactored some of the shared logic into a function based on the insights from his work.

**Comment by EclecticGriffin** [comment]
TIL rust won't even parse the tests if you aren't running them

**Comment by rachitnigam** [comment]
You can use the command `cargo check --all --all-targets` to get around this.
