### ISSUE TITLE
Expanding Primitives + Values > 64 Bits

### ISSUE THREAD

**Issue by almathaler** [cucapra/calyx#572]
Currently we can only process Values up to 64 bits, because the interiors of all primitives first convert Values to u64/i64, process, convert back to Values, return. 

Altering this behavior would involve processing Values + their BitVecs as bits, but where? If we do that in Values, then aren't we limited by that function's return value? But if that processing is done in Primitives, is that the right place...?

**Comment by yn224** [comment]
Just a note that we have found an issue with regards to how the comparison works in between value vectors (in the PR addressed above)
