### ISSUE TITLE
Print Memories based on the `@external` attribute

### ISSUE THREAD

**Issue by EclecticGriffin** [cucapra/calyx#591]
Rather than printing the internal state of all the memories, we should print only those with the `@external` attribute to more closely align with the verilator behavior.

Should we emit the internal state of all registers? Or do they also require an annotation?

**Comment by sampsyo** [comment]
Rad. I think probably just the memories, because AFAIK that's all the Verilator backend can expose too?

(It seems nice to have a flag to optionally dump all state, or perhaps just the registers, as an option.)

**Comment by EclecticGriffin** [comment]
A flag for the registers makes sense, it's useful to be able to inspect their state in some of the tests
