### ISSUE TITLE
Make the panics for the interpreter errors instead

### ISSUE THREAD

**Issue by EclecticGriffin** [cucapra/calyx#622]
What it says on the tin. The panic messages for the tests which we expect to fail cause a small headache because they depend on the line number of the panic. 

Ideally we would use proper error handling for these and other cases in the interpreter, though this will require some re-architecting.

**Comment by rachitnigam** [comment]
@EclecticGriffin does #631 completely fix this issue?

**Comment by EclecticGriffin** [comment]
#631 set some of the ground work but doesn't cover all the error cases that should be addressed. There are a few more deeper in the interpretation loop that are still panics and should probably be changed
