### ISSUE TITLE
[CIRCT] Add attributes.

### ISSUE THREAD

**Issue by cgyurgyik** [cucapra/calyx#659]
Pending review, attribute support for Calyx should be ready soon in [CIRCT #1727](https://github.com/llvm/circt/pull/1727).

## Instances, primitives

```
    %c0.in, %c0.go, %c0.clk, %c0.reset, %c0.out, %c0.done = calyx.instance "c0" @A : i8, i1, i1, i1, i8, i1
    %c1.in, %c1.go, %c1.clk, %c1.reset, %c1.out, %c1.done = calyx.instance "c1" @B {not_calyx_attr="foo", precious} : i1, i1, i1, i1, i1, i1
    %r.in, %r.write_en, %r.clk, %r.reset, %r.out, %r.done = calyx.register "r" : i8, i1, i1, i1, i8, i1
    %m0.addr0, %m0.write_data, %m0.write_en, %m0.clk, %m0.read_data, %m0.done = calyx.memory "m0"<[1] x 32> [1] {external = 32} : i1, i32, i1, i1, i32, i1
    %m1.addr0, %m1.addr1, %m1.write_data, %m1.write_en, %m1.clk, %m1.read_data, %m1.done = calyx.memory "m1"<[64, 64] x 8> [6, 6] : i6, i6, i8, i1, i1, i8, i1
    %a0.left, %a0.right, %a0.out = calyx.std_add "a0" {generated} : i32, i32, i32
    %s0.in, %s0.out = calyx.std_slice "s0" {generated} : i32, i8
```

For instances, the attribute dictionary is found directly before the types.

## Operations with region

```
calyx.par {
          calyx.enable @Group1 {static = 1}
          calyx.enable @Group3 {static = 2}
} {static = 2}
```
For operations with a region (control, components, groups, ...), the attribute dictionary is found after the region body. For the EnableOp, it is after the enabled group.

## Component ports

```
calyx.component @A(%in: i8, %go: i1 {go}, %clk: i1 {clk}, %reset: i1 {reset}) -> (%out: i8, %done: i1 {done}) { ... }
```

For ports, they are found after the port type.

## Other notes
- If the attribute is boolean, then `clk = 1` and `clk` are treated equivalently. I'm wondering if this will ever nip us in the butt. It may be better to define these as boolean integer, e.g. `{clk = 1 : i1 }` and always explicitly give their value. By default, integer attributes are `i64`.
- Calyx attributes for ports on instances is not supported yet. This will be a little bit different, and is discussed in [CIRCT #1744](https://github.com/llvm/circt/issues/1744).
- If an attribute isn't recognized as one of Calyx's attributes, it is simply not emitted. I think for the most part this is OK, since printing the attribute dictionary is optional?
- Attribute dictionary syntax found [here](https://mlir.llvm.org/docs/Dialects/Builtin/#dictionaryattr).

**Comment by rachitnigam** [comment]
> If the attribute is boolean, then clk = 1 and clk are treated equivalently. I'm wondering if this will ever nip us in the butt. It may be better to define these as boolean integer, e.g. {clk = 1 : i1 } and always explicitly give their value. By default, integer attributes are i64.

Calyx doesn't differentiate between boolean and integer attributes which means in #664, it would generate `{static}` for `@static(1)` which would crash the MLIR emitter on roundtripping:
```
        Assertion failed: (isBooleanAttribute && "Non-boolean attributes must provide an integer value."), function getAttribute, file /Users/rachitnigam/git/circt/lib/Dialect/Calyx/Export/CalyxEmitter.cpp, line 2
```

For now, we will always generate `{static = 1}` and `{go = 1}`.
