### ISSUE TITLE
[CIRCT] Unintended output.

### ISSUE THREAD

**Issue by cgyurgyik** [cucapra/calyx#666]
https://github.com/cucapra/calyx/blob/9cbe07a2f34198410ca51872f7efc5b13a7d4d02/tests/backend/circt/attributes.expect#L1-L5

**Comment by cgyurgyik** [comment]
Lacking flag to mark the backend in first line comment:
```
-b mlir
```

**Comment by rachitnigam** [comment]
Facepalm. Feel free to fix on master.
