### ISSUE TITLE
Example external `fud` stage

### ISSUE THREAD

**Issue by mortbopet** [cucapra/calyx#669]
While there exists some documentation for adding external stages to fud (https://capra.cs.cornell.edu/docs/calyx/fud/index.html#adding-external-stages), there is (as far as i can tell) no actual examples available for out-of-tree stages. I suspect that with an example to reference, I could have saved a good 30 minutes on trying to set up an external stage.

**Comment by rachitnigam** [comment]
@sgpthomas if you have an external stage lying somewhere, can you add a link to it? We can try to move something like mrxl to be an external stage so that we eventually have an in-tree example.

**Comment by sgpthomas** [comment]
Here's an example: https://github.com/sgpthomas/mandlebrot-fpga/blob/main/stage.py. Albeit this one is a little messy. I think moving mrxl to an external stage is probably a good idea. And I suppose we can now link to the circt one.
