### ISSUE TITLE
[fud] Enable local FPGA flow 

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/calyx#680]
@sgpthomas mentioned that the `xclbin` stage for `fud` currently only supports usage though SSH. We should make it work using a local pointer to a Vivado installation.

**Comment by rachitnigam** [comment]
@sampsyo do your changes make it possible to run FPGA execution locally? If so, we can close this issue.

**Comment by sampsyo** [comment]
Ah, yes! All set now.
