### ISSUE TITLE
[CIRCT] [fud] Add documentation for lowering MLIR programs.

### ISSUE THREAD

**Issue by cgyurgyik** [cucapra/calyx#689]
In case folks become interested in using Morten's new frontend, I think it would be good to add some specific instructions to complete the CIRCT round-trip (with examples).

**Comment by rachitnigam** [comment]
Concrete steps: Add a new CIRCT backend section to the docs and explain how to run the various tools to roundtrip examples.

**Comment by cgyurgyik** [comment]
Closed by #701.
