### ISSUE TITLE
[fud] Error when passing directories as top-level argument

### ISSUE THREAD

**Issue by mortbopet** [cucapra/calyx#694]
I'm running into an issue when trying to run the `resource-estimate` pass in isolation. This pass takes a directory as an input. To reproduce, run the following pass while pointing to an output vivado directory:

`fud exec --from synth-files --to resource-estimate /path/to/tmpvivadoproject`

which will throw an error related to the fact that only the base directory name, and not the absolute path, is being forwarded to the pass as an argument:
```
fud exec --from synth-files --to resource-estimate /path/to/tmpvivadoproject
Traceback (most recent call last):
  File "/home/morten/.local/lib/python3.8/site-packages/fud/stages/vivado/extract.py", line 57, in futil_extract
    impl_parser = rpt.RPTParser(
  File "/home/morten/.local/lib/python3.8/site-packages/fud/stages/vivado/rpt.py", line 13, in __init__
    with open(filepath, "r") as data:
FileNotFoundError: [Errno 2] No such file or directory: 'tmpvivadoproject/out/FutilBuild.runs/impl_1/main_utilization_placed.rpt'
```
The decision to only use the base directory name stems from here:
https://github.com/cucapra/calyx/blob/b287a07d6eba663da888a4f180e669fe1b24c0a1/fud/fud/utils.py#L85-L90

Replacing the above with the following fixes the issue:
```python
    @staticmethod
    def path_to_directory(data):
        if data.is_dir():
            return Directory(data)
         else: 
             raise errors.SourceConversionNotDirectory(data.name) 

```
Didn't submit a PR; wanted to hear out whether this is intentional behavior or not.

**Comment by rachitnigam** [comment]
Pinging @sgpthomas about this
