### ISSUE TITLE
[Tracking] Frontend data structure audit

### ISSUE THREAD

**Issue by EclecticGriffin** [cucapra/calyx#812]
This is a tracking issue to audit the types of data being used by the frontends to inform the future development of custom data formatting in the interpreter and debugger.

Frontends:

- [ ] Relay
- [ ] Dahlia
- [ ] Systolic
- [ ] NTT
- [ ] MrXL

**Comment by rachitnigam** [comment]
Just to clarify, this is not about data format but data structures right? I remember this came out of a conversation about supporting source-level data structure debugging.

**Comment by EclecticGriffin** [comment]
That's right, should probably rename it to data structure audit

**Comment by rachitnigam** [comment]
@EclecticGriffin is this still an action item for the interpreter/paper submission?

**Comment by EclecticGriffin** [comment]
This is not immediately relevant to the current submission target. We could consider this something of a stretch goal if we decide there is sufficient time to handle data structure variable translation and data structure reconstruction, but that seems unlikely for the current submission

**Comment by rachitnigam** [comment]
@EclecticGriffin are we still planning to work on this? If not, let's close

**Comment by rachitnigam** [comment]
I assume we're not going to work on this so closing the issue
