### ISSUE TITLE
[Interpreter] De-libaryify the interpreter

### ISSUE THREAD

**Issue by EclecticGriffin** [cucapra/calyx#813]
The interpreter/debugger is currently organized as a very time main program which calls into the library implementing all the actual features. Unlike the compiler infrastructure it's not clear that the interpreter should really be exposing a library at all. While this is far from critical, it is occasionally awkward to mark things as publicly facing because the tiny bin needs to use them when they should really only be used within the crate. Probably the crate should just be a bin and not a lib + bin together, though I'm happy to hear contrary opinions.

**Comment by sampsyo** [comment]
Here is one very silly reason to consider keeping the library! It would make it easier to make alternative frontends, like an interactive web GUI that works by compiling the library to WebAssembly (like we do with the compiler). Not sure we’ll ever do that, but it would be neat!

**Comment by EclecticGriffin** [comment]
Ah fair, that does make sense!

**Comment by EclecticGriffin** [comment]
Going to close this since I no longer think it's necessary
