### ISSUE TITLE
[Repo] Add Cargo.lock to the repo

### ISSUE THREAD

**Issue by EclecticGriffin** [cucapra/calyx#818]
Following the minor issues that came up when merging #816 it seems like we should probably commit the lock file to avoid this in the future (following a conversation with @sampsyo). 

Tagging @rachitnigam since this particular decision predates my involvement so I don't know the underlying reasons.

**Comment by sampsyo** [comment]
Seems like the thing to do! As I understand it, the recent-ish trend toward committing "lockfiles" for package manager is essentially to avoid CI surprises like the one referenced above.

**Comment by rachitnigam** [comment]
Seems like Rust people recommend it for binaries: https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries
