### ISSUE TITLE
[Interpreter] Remove the separate interpreter path

### ISSUE THREAD

**Issue by EclecticGriffin** [cucapra/calyx#839]
I'm not convinced we really need the separate interpreter path which only has partial overlap with the debugger since they are meant to do the same thing and need to be kept consistent with each-other.

The advantage to keeping the separate interpreter path is that it is a bit faster than the debugger path because it doesn't need to construct a tree of control interpreters, though in the future a better state representation may allow the debugger to have a similar speed.

**Comment by rachitnigam** [comment]
I wholeheartedly! I'm not convinced that the separation needs to exist and makes it kind of hard to figure out why certain inconsistencies exist in the two kinds of simulation (interpreter vs debugger run through)
