### ISSUE TITLE
Pass to inline constant wire assignments and remove unused combinational assignments

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/calyx#869]
Constant wire assignments look like:
```
x.in = y.out;
```
And allow for all uses of `x.out` to be replaced with `y.out`. This obviously requires baking in reasoning about the `std_wire` component but I think `std_wire` and `std_reg` should be core to the language anyways.

Unused assignments make sense in the context of `comb primitive` only. If the output port of a primitive is never read from, all writes to the input ports can be safely removed. This reasoning should only be applied to `comb primitive` definition but can eventually be extended to `@read_together` specifications.

**Comment by sampsyo** [comment]
Sounds nice. I agree that "baking in" awareness of `std_wire` is quite reasonable, much like the passes we already have that deal specifically with registers.
