### ISSUE TITLE
[Tracking] Interpreter Optimization Ideas

### ISSUE THREAD

**Issue by EclecticGriffin** [cucapra/calyx#878]
## Parallelism

1. Execute par blocks in parallel
2. Parallel execution of assignments (in group execution)

The first of these is more likely to be useful while the latter might not always be faster.

## Performance tuning
3. Avoid executing cells which have not had a value change (during combinational convergence loop)
4. Use dataflow ordering to evaluate the group directly rather than iterating until combinational convergence. #893 

There are definitely other things and I will update this issue as I remember them and link the appropriate issues for particular implementation proposals.

**Comment by rachitnigam** [comment]
The tracker is about a year old so let's discuss and update it or close it

**Comment by EclecticGriffin** [comment]
Closing: stale and not up to date with current efforts
