### ISSUE TITLE
Interpreter mode to validate `@bound` loops

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/calyx#900]
The interpreter can provide two capabilities that would be useful:
1. It can use the `@bound` annotation instead of the loop condition to decide when to exit a loop, and
2. It can validate existing `@bound` annotations to check if they are correct. This can be quite useful in the case of "pass-by-reference" components which might implicitly encode a bound in the loop and use the values in the wrong context.

**Comment by EclecticGriffin** [comment]
At first glance this seems pretty reasonable and relatively easy to implement at least for number 2.

1 is also straightforward though I don't know how much work it really saves us, could be worthwhile but hard for me to say a priori
