### ISSUE TITLE
Website - Systolic Array generator gives 404 Not found

### ISSUE THREAD

**Issue by JosseVanDelm** [cucapra/calyx#950]
Hi,

Just a quick issue to inform you that the link on your webpage https://calyxir.org/ the link to the systolic array generator
(https://capra.cs.cornell.edu/docs/calyx/frontends/systolic-array.html) results in a 404 not found.

I believe it should point to https://docs.calyxir.org/frontends/systolic-array.html ?

Best regards,

Josse

**Comment by rachitnigam** [comment]
Fixed in https://github.com/cucapra/calyx-site/commit/897c6197c498afbef47f4780febc038c27c48564, thanks!
