### ISSUE TITLE
[???] Cholesky Benchmark failing on Verilator 4.028

### ISSUE THREAD

**Issue by EclecticGriffin** [cucapra/calyx#963]
This is happening on Havarti and its unclear quite what is going on. Since it doesn't seem to reproduce locally it might just be an issue with the old version of verilator running on the machine.

**Comment by rachitnigam** [comment]
Can you paste the exact error message?

**Comment by EclecticGriffin** [comment]
It's a disagreement between the golden and computed values of the sqrt. I'll go find the exact message

**Comment by EclecticGriffin** [comment]
```
[135] %Error: tmpaefd1okc:118: Assertion failed in TOP.main.sqrt0:
sqrt: Computed and golden outputs do not match!
input: 429496782
expected: 0
computed: 65535
```

**Comment by rachitnigam** [comment]
Seems like an int max overflow

**Comment by EclecticGriffin** [comment]
it does indeed! I assume updating Havarti's verilator will probably fix this I just haven't gotten around to looking up the build from source instructions again

**Comment by EclecticGriffin** [comment]
closing since updating the installation to v4.220 seems to have resolved the issue on Havarti
