### ISSUE TITLE
Source position integration through CIRCT SCF

### ISSUE THREAD

**Issue by EclecticGriffin** [cucapra/calyx#974]
Opening the issue for @cgyurgyik as promised in the Friday meeting.

Details of the source location metadata format are found in (#971 with minor tweaks in #973). I can link the relevant portions of the code as needed. Both these PRs include support in the relay_visitor as an example of this in practice.

**Comment by EclecticGriffin** [comment]
#977

**Comment by EclecticGriffin** [comment]
```
fud e --to debugger lenet.relay -s relay.flags "--write-metadata meta.json" -s debugger.flags "--source meta.json" -q 
```

**Comment by rachitnigam** [comment]
Looks like this has been fixed. @EclecticGriffin feel free to re-open if that is not the case
